* TODO [#A] Linking to an entry in the same wiki
:PROPERTIES:
:CREATED_TIME: [2020-02-17 Mon 04:13]
:END:
When it inserts a link to an entry in the same wiki, it should omit the directory ID.

Perhaps it can be implemented by advising =org-link-make-string= to modify the link.
This is a hack, but this seems to be the only way according to the current implementation of =org-insert-link=.
I will a custom variable to enable this feature.
* TODO [#A] Linking to non-org files in wiki directories
:PROPERTIES:
:CREATED_TIME: [2020-02-17 Mon 04:13]
:END:
It should be able to store a link to a non-org file in a wiki directory.
Inline images inserted via the link scheme should be displayed properly.
* TODO Recursive file search
:PROPERTIES:
:CREATED_TIME: [2020-02-17 Mon 04:16]
:END:
* TODO Prohibit refiling from wiki
:PROPERTIES:
:CREATED_TIME: [2020-02-20 Thu 03:19]
:END:
It may be important to prohibit refiling entries that are already in a wiki.
Refiling wiki entries to other places can cause deadlinks, which makes the wiki much useless.
It is possible to implement this as a function advice, but a better solution would be to define a minor mode =org-multi-wiki-mode= which can be enabled inside =org-mode=.
