name: lint

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.org'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - org-multi-wiki
          - helm-org-multi-wiki
    steps:
    - uses: actions/checkout@v2
    - uses: akirak/emacs-package@master
    - run: melpa-check lint ${{ matrix.package }}
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - org-multi-wiki
          - helm-org-multi-wiki
        emacs-version:
          - emacs-26-1
          - emacs-26-2
          - emacs-26-3
    steps:
    - uses: actions/checkout@v2
    - uses: akirak/emacs-package@master
    - run: melpa-check byte-compile -e ${{ matrix.emacs }} ${{ matrix.package }}
    - run: melpa-check buttercup -e ${{ matrix.emacs }} ${{ matrix.package }}
