name: lint

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.org'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - emacs-26-1
          - emacs-26-2
          - emacs-26-3
    steps:
    - name: install nix
      uses: cachix/install-nix-action@v5
    - name: install cachix
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install
    - name: enable cachix for emacs-ci
      run: cachix use emacs-ci
    - name: check if nix is installed
      run: nix-env --version
    - uses: actions/checkout@v1
    - run: nix-channel --add https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz emacs-ci
    - run: nix-channel --update
    - name: Run checkdoc on all packages
      run: nix-build --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A checkdoc --no-out-link --quiet .melpa-check
    - name: Run package-lint on org-multi-wiki
      run: nix-shell --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A package-lint.org-multi-wiki --pure --quiet .melpa-check
    - name: Run package-lint on helm-org-multi-wiki
      run: nix-shell --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A package-lint.helm-org-multi-wiki --pure --quiet .melpa-check
    - name: Byte-compile all files
      run: nix-build --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A byte-compile --no-out-link --quiet .melpa-check
    - name: Run tests
      run: nix-shell --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A buttercup --pure --quiet .melpa-check
