name: lint

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.org'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - emacs-26-1
          - emacs-26-2
          - emacs-26-3
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    # cachix-action requires a name, so I won't use it
    # - uses: cachix/cachix-action@v6
    - run: nix-env -iA cli.gh-action -f https://github.com/akirak/melpa-check/archive/v3.tar.gz
    - run: melpa-check deps
    - name: Run checkdoc on all packages
      run: nix-shell -A checkdoc --pure --quiet .melpa-check
    - name: Run package-lint on org-multi-wiki
      run: nix-shell -A package-lint.org-multi-wiki --pure --quiet .melpa-check
    - name: Run package-lint on helm-org-multi-wiki
      run: nix-shell -A package-lint.helm-org-multi-wiki --pure --quiet .melpa-check
    - name: Byte-compile all files
      run: nix-build --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A byte-compile --no-out-link --quiet .melpa-check
    - name: Run tests
      run: |
        nix-build --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A prepareButtercup --no-build-output .melpa-check
        nix-shell --arg emacs "(import <emacs-ci>).${{ matrix.emacs-version }}" -A buttercup.org-multi-wiki --pure --quiet .melpa-check
